name: Build and Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify SSH Key
        run: |
          echo "Verifying SSH key..."
          echo "${{ secrets.EC2_KEY }}" > tmp_key
          chmod 600 tmp_key
          ssh-keygen -l -f tmp_key  # This should show the fingerprint
          rm tmp_key

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: target/*.jar
          target: /home/ubuntu/
          strip_components: 0
          overwrite: true
          timeout: 60s

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Find and kill existing Java processes
            sudo pkill -f 'java -jar' || true
            # Wait for process termination
            sleep 3
            # Move jar to dedicated location
            JAR_FILE=$(ls /home/ubuntu/*.jar | head -1)
            sudo mv "$JAR_FILE" /opt/app.jar
            # Start new instance
            nohup sudo java -jar /opt/app.jar > /var/log/app.log 2>&1 &
            # Verify it's running
            sleep 5
            pgrep -fl 'java -jar'